//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopSort.UI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopSort.UI.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создаваемая папка:.
        /// </summary>
        public static string FirstSettingsCatalogText {
            get {
                return ResourceManager.GetString("FirstSettingsCatalogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsoft Word.
        /// </summary>
        public static string FirstSettingsCheckBox1 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архивы.
        /// </summary>
        public static string FirstSettingsCheckBox10 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронные книги.
        /// </summary>
        public static string FirstSettingsCheckBox11 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 1.
        /// </summary>
        public static string FirstSettingsCheckBox12 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 2.
        /// </summary>
        public static string FirstSettingsCheckBox13 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 3.
        /// </summary>
        public static string FirstSettingsCheckBox14 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 4.
        /// </summary>
        public static string FirstSettingsCheckBox15 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 5.
        /// </summary>
        public static string FirstSettingsCheckBox16 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 6.
        /// </summary>
        public static string FirstSettingsCheckBox17 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 7.
        /// </summary>
        public static string FirstSettingsCheckBox18 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 8.
        /// </summary>
        public static string FirstSettingsCheckBox19 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsoft Excel.
        /// </summary>
        public static string FirstSettingsCheckBox2 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 9.
        /// </summary>
        public static string FirstSettingsCheckBox20 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон 10.
        /// </summary>
        public static string FirstSettingsCheckBox21 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsoft Access.
        /// </summary>
        public static string FirstSettingsCheckBox3 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsoft Project.
        /// </summary>
        public static string FirstSettingsCheckBox4 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsoft PowerPoint.
        /// </summary>
        public static string FirstSettingsCheckBox5 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsoft OneNote.
        /// </summary>
        public static string FirstSettingsCheckBox6 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текстовые файлы.
        /// </summary>
        public static string FirstSettingsCheckBox7 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображения.
        /// </summary>
        public static string FirstSettingsCheckBox8 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мультимедиа.
        /// </summary>
        public static string FirstSettingsCheckBox9 {
            get {
                return ResourceManager.GetString("FirstSettingsCheckBox9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширения:.
        /// </summary>
        public static string FirstSettingsExtensionText {
            get {
                return ResourceManager.GetString("FirstSettingsExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иконка для папки:.
        /// </summary>
        public static string FirstSettingsIconText {
            get {
                return ResourceManager.GetString("FirstSettingsIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только новые файлы.
        /// </summary>
        public static string FirstSettingsNewFilesText {
            get {
                return ResourceManager.GetString("FirstSettingsNewFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только старые файлы.
        /// </summary>
        public static string FirstSettingsOldFilesText {
            get {
                return ResourceManager.GetString("FirstSettingsOldFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки // Фильтрация.
        /// </summary>
        public static string FirstSettingsTitle {
            get {
                return ResourceManager.GetString("FirstSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Desktop Sort - Это мгновенная сортировка файлов по папкам. Если придя за свое рабочее место вы обнаружите, что весь рабочий стол забит разными файлами, а ваш внутренний перфекционизм желает от этого всего избавиться, то Desktop Sort программа именно для вас!.
        /// </summary>
        public static string InfoSettingsDescriptionText {
            get {
                return ResourceManager.GetString("InfoSettingsDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытый исходный код! C# + WPF + MVVM / Дата старта 31.12.20.
        /// </summary>
        public static string InfoSettingsOpenSourceText {
            get {
                return ResourceManager.GetString("InfoSettingsOpenSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки // О программе.
        /// </summary>
        public static string InfoSettingsTitle {
            get {
                return ResourceManager.GetString("InfoSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Благодарности.
        /// </summary>
        public static string InfoSettingsTitle2 {
            get {
                return ResourceManager.GetString("InfoSettingsTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string InfoSettingsTitle3 {
            get {
                return ResourceManager.GetString("InfoSettingsTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать.
        /// </summary>
        public static string MainButtonCopy {
            get {
                return ResourceManager.GetString("MainButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить.
        /// </summary>
        public static string MainButtonCut {
            get {
                return ResourceManager.GetString("MainButtonCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игнорировать.
        /// </summary>
        public static string MainButtonIgnore {
            get {
                return ResourceManager.GetString("MainButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите путь до папки.
        /// </summary>
        public static string MainLeftText {
            get {
                return ResourceManager.GetString("MainLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание, проверка на обновления приложения была выключена в настройках.
        /// </summary>
        public static string MessageIsUpdateFalse {
            get {
                return ResourceManager.GetString("MessageIsUpdateFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется обновление! Релиз:.
        /// </summary>
        public static string MessageIsUpdateTrue {
            get {
                return ResourceManager.GetString("MessageIsUpdateTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы используете актуальную версию!.
        /// </summary>
        public static string MessageNoUpdates {
            get {
                return ResourceManager.GetString("MessageNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки для обновления приложения были применены.
        /// </summary>
        public static string MessageUsingSettingsForUpdate {
            get {
                return ResourceManager.GetString("MessageUsingSettingsForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать! Версия: .
        /// </summary>
        public static string MessageWelcomeNVersion {
            get {
                return ResourceManager.GetString("MessageWelcomeNVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите путь до заднего изображения:.
        /// </summary>
        public static string SecondSettingsBackgroundText {
            get {
                return ResourceManager.GetString("SecondSettingsBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверять обновления автоматически.
        /// </summary>
        public static string SecondSettingsCheckAutoUpdate {
            get {
                return ResourceManager.GetString("SecondSettingsCheckAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить первоначальную папку [Не рекомендуется].
        /// </summary>
        public static string SecondSettingsDeleteFirstDirectory {
            get {
                return ResourceManager.GetString("SecondSettingsDeleteFirstDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключить задний фон.
        /// </summary>
        public static string SecondSettingsDisableBackground {
            get {
                return ResourceManager.GetString("SecondSettingsDisableBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор темы:.
        /// </summary>
        public static string SecondSettingsThemeText {
            get {
                return ResourceManager.GetString("SecondSettingsThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки // Параметры приложения.
        /// </summary>
        public static string SecondSettingsTitle {
            get {
                return ResourceManager.GetString("SecondSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string UpdateControlButtonDownload {
            get {
                return ResourceManager.GetString("UpdateControlButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что нового?.
        /// </summary>
        public static string UpdateControlText {
            get {
                return ResourceManager.GetString("UpdateControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки // Обновление.
        /// </summary>
        public static string UpdateControlTitle {
            get {
                return ResourceManager.GetString("UpdateControlTitle", resourceCulture);
            }
        }
    }
}
